# Generated by Django 2.1.5 on 2020-05-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200507_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
